# docker-compose.override.yml
version: "2"
services:
  nginx:
      build:
          args:
              - WEB_SSL=true
      environment:
        - MONGODB=${MONGODB}
  certbot:
      environment:
        - CN=fastcheckout.me
        - EMAIL=hristov.reading@gmail.com